version: '3'
services:
   app:
    build: .
    command: bash -c "/app/runserver.sh"
    restart: always
    volumes:
      - .:/app
    
   nginx:
    build: ./nginx_folder
    volumes:
      - /var/log/nginx/:/var/log/nginx/
    ports:
      - "80:80"
    depends_on:
      - app

      

